# Exercício:

## 1 – Um objeto composto multidimensional (matriz) pode receber  objeto composto unidimensional (vetor)?

In [103]:
#Sim, uma matriz pode receber um vetor
##Desde que: inserido como linha ou coluna indexando da matriz (indexando) e que tenha mesmo formato de tamanho

In [104]:
##Instanciando uma matriz do tipo lista
matriz = [
    [1, 2, 3], 
    [4, 5, 6]
    ]

vetor = [7, 8, 9]
matriz[1] = vetor

print(matriz)

[[1, 2, 3], [7, 8, 9]]

## 2 – No exercício 9 da última aula, foram instanciadas 5 listas. Instancie um objeto composto multidimensional da classe lista com estes cinco vetores. Recupere a matriz.

In [105]:
##Exercício 9
genes_lista = ['gapdh', 'icam', 'mcp1', 'tgfb', 'sdc1']
 
i = 0
gapdh = [
    len(genes_lista[i]),
    genes_lista[i][:2],
    genes_lista[i].count("a"),
    "hu" in genes_lista[i]
]
print(gapdh)

i = 1
icam = [
    len(genes_lista[i]),
    genes_lista[i][:2],
    genes_lista[i].count("a"),
    "hu" in genes_lista[i]
]
print(icam)

i = 2
mcp1 = [
    len(genes_lista[i]),
    genes_lista[i][:2],
    genes_lista[i].count("a"),
    "hu" in genes_lista[i]
]
print(mcp1)

i = 3
tgfb = [
    len(genes_lista[i]),
    genes_lista[i][:2],
    genes_lista[i].count("a"),
    "hu" in genes_lista[i]
]
print(tgfb)

i = 4
sdc1 = [
    len(genes_lista[i]),
    genes_lista[i][:2],
    genes_lista[i].count("a"),
    "hu" in genes_lista[i]
]
print(sdc1)

[5, 'ga', 1, False]
[4, 'ic', 1, False]
[4, 'mc', 0, False]
[4, 'tg', 0, False]
[4, 'sd', 0, False]

In [106]:
matriz = [gapdh, 
          icam, 
          mcp1, 
          tgfb, 
          sdc1]

print(matriz)

[[5, 'ga', 1, False], [4, 'ic', 1, False], [4, 'mc', 0, False], [4, 'tg', 0, False], [4, 'sd', 0, False]]

## 3 – Copie e converta o objeto instanciado no exercício 2 para um NumPy array. Recupere o array.

In [107]:
import numpy as np

In [108]:
array = np.array(matriz)
print(array)

[['5' 'ga' '1' 'False']
 ['4' 'ic' '1' 'False']
 ['4' 'mc' '0' 'False']
 ['4' 'tg' '0' 'False']
 ['4' 'sd' '0' 'False']]

## 4 – Recupere todos os itens do terceiro gene.

In [109]:
terceiro_gene = matriz[2]
print(terceiro_gene)

[4, 'mc', 0, False]

## 5 – Verifique se todos os nomes dos genes tem ou não os caracteres 'hu'.

In [110]:
genes_lista

todos_matriz = [
"hu" in genes_lista[0],
"hu" in genes_lista[1],
"hu" in genes_lista[2],
"hu" in genes_lista[3],
"hu" in genes_lista[4]
]
print(todos_matriz)

[False, False, False, False, False]

## 6 – Recupere do segundo e quarto genes, os dois primeiros caracteres dos nomes e os quantitativos de 'a' presentes nos nomes dos genes.

In [111]:
segundo_gene = matriz[1]
print(segundo_gene)

[4, 'ic', 1, False]

In [112]:
segundo_gene = [    
genes_lista[1][:2],
genes_lista[1].count("a")
]
print(segundo_gene)

['ic', 1]

In [113]:
quarto_gene = matriz[3]
print(quarto_gene)

[4, 'tg', 0, False]

In [114]:
quarto_gene = [    
genes_lista[3][:2],
genes_lista[3].count("a")
]
print(quarto_gene)

['tg', 0]

## 7 – Converta o objeto instanciado no exercício 10 da aula anterior para uma DataFrame Pandas. Nesta DataFrame, os index devem ser os nomes dos genes e cada coluna deve ter um nome que indique seu conteúdo. Recupere a DataFrame.

In [115]:
import pandas as pd

In [116]:
df = pd.DataFrame(
    matriz,
    index=genes_lista,
    columns=["n_caracteres", "2_caracteres", "num_a", "tem_hu"]
)
df

       n_caracteres 2_caracteres  num_a  tem_hu
gapdh             5           ga      1   False
icam              4           ic      1   False
mcp1              4           mc      0   False
tgfb              4           tg      0   False
sdc1              4           sd      0   False

In [121]:
#Exportando arquivo
df.to_csv ("arquivoaula6.csv")

## 8 – Da DataFrame do exercício anterior recupere os números de caracteres e quantas vezes aparece o caractere ‘a’ de todos os genes.

In [ ]:
dfcarax = df [["n_caracteres", "num_a"]]
dfcarax

       n_caracteres  num_a
gapdh             5      1
icam              4      1
mcp1              4      0
tgfb              4      0
sdc1              4      0

## 9 – Da DataFrame do exercício anterior recupere se no nome aparecem os caracteres ‘hu’, para o primeiro e o terceiro genes.

In [ ]:
df.iloc[[0, 2]][["tem_hu"]]

       tem_hu
gapdh   False
mcp1    False

## 10 – Importe o data.csv (dados de seguro na Flórida em 2012) para uma DataFrame. Armazene em um dicionário o número de entradas, uma lista com as classes das colunas e outra lista com o número de elementos de cada classe, três listas, contendo a média, o desvio padrão e o terceiro quartil da primeira, quarta e nona colunas . Recupere o dicionário.

In [ ]:
import pandas as pd

In [ ]:
dfseguro = pd.read_csv("data.csv")
dfseguro.head()

,policyID,statecode,county,eq_site_limit,hu_site_limit,fl_site_limit,fr_site_limit,tiv_2011,tiv_2012,eq_site_deductible,hu_site_deductible,fl_site_deductible,fr_site_deductible,point_latitude,point_longitude,line,construction,point_granularity
0,119736,FL,CLAY COUNTY,498960.0,498960.00,498960.0,498960.0,498960.00,792148.90,0.0,9979.2,0.0,0,30.102261,-81.711777,Residential,Masonry,1
1,448094,FL,CLAY COUNTY,1322376.3,1322376.30,1322376.3,1322376.3,1322376.30,1438163.57,0.0,0.0,0.0,0,30.063936,-81.707664,Residential,Masonry,3
2,206893,FL,CLAY COUNTY,190724.4,190724.40,190724.4,190724.4,190724.40,192476.78,0.0,0.0,0.0,0,30.089579,-81.700455,Residential,Wood,1
3,333743,FL,CLAY COUNTY,0.0,79520.76,0.0,0.0,79520.76,86854.48,0.0,0.0,0.0,0,30.063236,-81.707703,Residential,Wood,3
4,172534,FL,CLAY COUNTY,0.0,254281.50,0.0,254281.5,254281.50,246144.49,0.0,0.0,0.0,0,30.060614,-81.702675,Residential,Wood,1

In [ ]:
entradas = dfseguro.shape
entradas

(36634, 18)

In [ ]:
classes = [dfseguro.dtypes.unique()]
classes

[array([dtype('int64'), dtype('O'), dtype('float64')], dtype=object)]

In [ ]:
numero_classes = [dfseguro.dtypes.value_counts()]
numero_classes

[float64    11
 object      4
 int64       3
 Name: count, dtype: int64]

In [ ]:
colunas = dfseguro.iloc[:, [0, 3, 8]]
colunas

       policyID  eq_site_limit    tiv_2012
0        119736       498960.0   792148.90
1        448094      1322376.3  1438163.57
2        206893       190724.4   192476.78
3        333743            0.0    86854.48
4        172534            0.0   246144.49
...         ...            ...         ...
36629    404309            0.0   155065.65
36630    465875      1297057.5  1577500.79
36631    791209       173286.9   205527.97
36632    322627      1499781.6  1768782.43
36633    398149       373488.3   596003.67

[36634 rows x 3 columns]

In [ ]:
listamedia = [colunas.mean]
listamedia

[<bound method DataFrame.mean of        policyID  eq_site_limit    tiv_2012
 0        119736       498960.0   792148.90
 1        448094      1322376.3  1438163.57
 2        206893       190724.4   192476.78
 3        333743            0.0    86854.48
 4        172534            0.0   246144.49
 ...         ...            ...         ...
 36629    404309            0.0   155065.65
 36630    465875      1297057.5  1577500.79
 36631    791209       173286.9   205527.97
 36632    322627      1499781.6  1768782.43
 36633    398149       373488.3   596003.67

 [36634 rows x 3 columns]>]

In [ ]:
listadesvio = [colunas.std]
listadesvio

[<bound method DataFrame.std of        policyID  eq_site_limit    tiv_2012
 0        119736       498960.0   792148.90
 1        448094      1322376.3  1438163.57
 2        206893       190724.4   192476.78
 3        333743            0.0    86854.48
 4        172534            0.0   246144.49
 ...         ...            ...         ...
 36629    404309            0.0   155065.65
 36630    465875      1297057.5  1577500.79
 36631    791209       173286.9   205527.97
 36632    322627      1499781.6  1768782.43
 36633    398149       373488.3   596003.67

 [36634 rows x 3 columns]>]

In [ ]:
quartil3 = [colunas.quantile(0.75)]
quartil3

[policyID         7.742520e+05
 eq_site_limit    0.000000e+00
 tiv_2012         1.128871e+06
 Name: 0.75, dtype: float64]

In [ ]:
dicionario_seguro = {
    "entrada": entradas,
    "classes": classes,
    "num_classes": numero_classes,
    "media": listamedia,
    "desvio_pad": listadesvio,
    "quartil": quartil3
}
dicionario_seguro

{'entrada': (36634, 18),
 'classes': [array([dtype('int64'), dtype('O'), dtype('float64')], dtype=object)],
 'num_classes': [float64    11
  object      4
  int64       3
  Name: count, dtype: int64],
 'media': [<bound method DataFrame.mean of        policyID  eq_site_limit    tiv_2012
  0        119736       498960.0   792148.90
  1        448094      1322376.3  1438163.57
  2        206893       190724.4   192476.78
  3        333743            0.0    86854.48
  4        172534            0.0   246144.49
  ...         ...            ...         ...
  36629    404309            0.0   155065.65
  36630    465875      1297057.5  1577500.79
  36631    791209       173286.9   205527.97
  36632    322627      1499781.6  1768782.43
  36633    398149       373488.3   596003.67

  [36634 rows x 3 columns]>],
 'desvio_pad': [<bound method DataFrame.std of        policyID  eq_site_limit    tiv_2012
  0        119736       498960.0   792148.90
  1        448094      1322376.3  1438163.57
  2        206893       190724.4   192476.78
  3        333743            0.0    86854.48
  4        172534            0.0   246144.49
  ...         ...            ...         ...
  36629    404309            0.0   155065.65
  36630    465875      1297057.5  1577500.79
  36631    791209       173286.9   205527.97
  36632    322627      1499781.6  1768782.43
  36633    398149       373488.3   596003.67

  [36634 rows x 3 columns]>],
 'quartil': [policyID         7.742520e+05
  eq_site_limit    0.000000e+00
  tiv_2012         1.128871e+06
  Name: 0.75, dtype: float64]}