In [1]:
num_1 = 4
num_2 = 2
print(num_1 + num_2)

6

In [4]:
tupla_1 = (1, 2, 3)
tupla_2 = (1, 20, 3)
print(tupla_1 + tupla_2)

(1, 2, 3, 1, 20, 3)

In [5]:
tupla_1 += tupla_2
(tupla_1)

(1, 2, 3, 1, 20, 3)

In [7]:
tupla_1 = tupla_1 += tupla_2
diplay(tupla_1)
display(tupla_2)

SyntaxError: invalid syntax (1568324762.py, line 1)

In [9]:
display (list(tupla_1))
display (tupla_1)

[1, 2, 3, 1, 20, 3, 1, 20, 3]

(1, 2, 3, 1, 20, 3, 1, 20, 3)

In [11]:
dict_1.update(dict_2)
dict_1

NameError: name 'dict_1' is not defined

In [14]:
lista_da_tupla_1 = list (tupla_1)
lista_da_tupla_1

[1, 2, 3, 1, 20, 3, 1, 20, 3]

In [15]:
lista_da_tupla 1[2] += 2
lista_da_tupla_1

SyntaxError: invalid syntax (1371589639.py, line 1)

In [12]:
import numpy as np

In [ ]:
array = np.array(lista_da_tupla_1)
array

array([ 1,  2,  3,  1, 20,  3,  1, 20,  3])

In [25]:
array += 2
array

array([  3,   6,  11,   3, 402,  11,   3, 402,  11])

In [26]:
array *= array
array

array([  1,   4,   9,   1, 400,   9,   1, 400,   9])

In [29]:
np.insert(arr=array, obj=2, values=100)

array([  1,   4, 100,   9,   1, 400,   9,   1, 400,   9])

In [30]:
len(np.insert(arr=array, obj=2, values=100))

10

In [36]:
np.insert(arr=np.array(['a''b']), obj=2, values=(0,1))

IndexError: index 2 is out of bounds for axis 0 with size 1

In [39]:
array = np.array(lista_da_tupla_1)
array.shape

(9,)

In [49]:
array = np.array(lista_da_tupla_1).reshape(3, 3)
array.shape

(3, 3)

In [50]:
import pandas as pd

In [52]:
df = pd.DataFrame(array)
df

   0   1  2
0  1   2  3
1  1  20  3
2  1  20  3

In [54]:
df += 2
df

   0   1  2
0  5   6  7
1  5  24  7
2  5  24  7

In [55]:
df += df
df

    0   1   2
0  10  12  14
1  10  48  14
2  10  48  14

In [61]:
##array_ones = np.ones_like(df)
array_ones = np.zeros_like(df)
array_ones[1,1] = 100
array_ones

array([[  0,   0,   0],
       [  0, 100,   0],
       [  0,   0,   0]])

In [62]:
df += array_ones
df

    0    1   2
0  11   13  15
1  11  248  15
2  11   49  15